import { CatalogProduct } from './catalog-types';

export const CATALOG_DATA: CatalogProduct[] = [
  {
    id: 'MCU-001',
    name: 'Arduino Uno R3',
    part_number: 'A000066',
    category: 'Electrical',
    subcategory: 'Microcontrollers',
    description: 'ATmega328P board, 14 digital I/O, 6 analog, 16MHz, USB. The most popular beginner microcontroller.',
    specifications: {'MCU': 'ATmega328P', 'Clock': '16 MHz', 'Flash': '32 KB', 'SRAM': '2 KB', 'Digital I/O': '14', 'Analog In': '6', 'Voltage': '5V'},
    price_inr: 649,
    price_usd: 7.8,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 850,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=Arduino+Uno',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=Arduino+Uno+R3', 'Flipkart': 'https://www.flipkart.com/search?q=Arduino+Uno+R3', 'Robu.in': 'https://robu.in/?s=Arduino+Uno+R3'},
    alternatives: ['MCU-002', 'MCU-003', 'MCU-004'],
    tags: ['arduino', 'microcontroller', 'atmega328p', 'beginner'],
    manufacturer: 'Arduino',
    rating: 4.7,
    reviews: 28500,
  },
  {
    id: 'MCU-002',
    name: 'ESP8266 NodeMCU V3',
    part_number: 'ESP8266-12E',
    category: 'Electrical',
    subcategory: 'Microcontrollers',
    description: 'Wi-Fi microcontroller, 80MHz, 4MB flash, 11 GPIO, 802.11 b/g/n. Best for IoT projects.',
    specifications: {'MCU': 'ESP8266EX', 'Clock': '80 MHz', 'Flash': '4 MB', 'GPIO': '11', 'WiFi': '802.11 b/g/n', 'Voltage': '3.3V'},
    price_inr: 299,
    price_usd: 3.6,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 1200,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=ESP8266',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=ESP8266+NodeMCU+V3', 'Flipkart': 'https://www.flipkart.com/search?q=ESP8266+NodeMCU+V3', 'Robu.in': 'https://robu.in/?s=ESP8266+NodeMCU+V3'},
    alternatives: ['MCU-003', 'MCU-001'],
    tags: ['esp8266', 'wifi', 'iot', 'nodemcu'],
    manufacturer: 'Espressif',
    rating: 4.5,
    reviews: 19200,
  },
  {
    id: 'MCU-003',
    name: 'ESP32 DevKit V1',
    part_number: 'ESP32-WROOM-32',
    category: 'Electrical',
    subcategory: 'Microcontrollers',
    description: 'Dual-core 240MHz, Wi-Fi+BT, 38 GPIO, 4MB flash. Best all-round IoT microcontroller.',
    specifications: {'MCU': 'ESP32', 'Clock': '240 MHz', 'Flash': '4 MB', 'GPIO': '38', 'WiFi': '802.11 b/g/n', 'BT': '4.2 BLE', 'Voltage': '3.3V'},
    price_inr: 399,
    price_usd: 4.8,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 980,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=ESP32',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=ESP32+DevKit+V1', 'Flipkart': 'https://www.flipkart.com/search?q=ESP32+DevKit+V1', 'Robu.in': 'https://robu.in/?s=ESP32+DevKit+V1'},
    alternatives: ['MCU-002', 'MCU-001'],
    tags: ['esp32', 'wifi', 'bluetooth', 'iot', 'dual-core'],
    manufacturer: 'Espressif',
    rating: 4.8,
    reviews: 32100,
  },
  {
    id: 'MCU-004',
    name: 'Arduino Nano',
    part_number: 'A000005',
    category: 'Electrical',
    subcategory: 'Microcontrollers',
    description: 'Compact ATmega328P board, breadboard-friendly, 22 I/O pins, 16MHz.',
    specifications: {'MCU': 'ATmega328P', 'Clock': '16 MHz', 'Flash': '32 KB', 'GPIO': '22', 'Voltage': '5V', 'Size': '18x45mm'},
    price_inr: 349,
    price_usd: 4.2,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 760,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=Arduino+Nano',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=Arduino+Nano', 'Flipkart': 'https://www.flipkart.com/search?q=Arduino+Nano', 'Robu.in': 'https://robu.in/?s=Arduino+Nano'},
    alternatives: ['MCU-001', 'MCU-009'],
    tags: ['arduino', 'nano', 'compact', 'atmega328p'],
    manufacturer: 'Arduino',
    rating: 4.6,
    reviews: 21000,
  },
  {
    id: 'MCU-005',
    name: 'Arduino Mega 2560',
    part_number: 'A000047',
    category: 'Electrical',
    subcategory: 'Microcontrollers',
    description: '54 digital I/O, 16 analog, 256KB flash. For complex multi-sensor projects.',
    specifications: {'MCU': 'ATmega2560', 'Clock': '16 MHz', 'Flash': '256 KB', 'Digital I/O': '54', 'Analog In': '16', 'Voltage': '5V'},
    price_inr: 899,
    price_usd: 10.8,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 420,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=Arduino+Mega',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=Arduino+Mega+2560', 'Flipkart': 'https://www.flipkart.com/search?q=Arduino+Mega+2560', 'Robu.in': 'https://robu.in/?s=Arduino+Mega+2560'},
    alternatives: ['MCU-001'],
    tags: ['arduino', 'mega', 'atmega2560', 'high-io'],
    manufacturer: 'Arduino',
    rating: 4.6,
    reviews: 15800,
  },
  {
    id: 'MCU-006',
    name: 'Raspberry Pi Pico',
    part_number: 'SC0915',
    category: 'Electrical',
    subcategory: 'Microcontrollers',
    description: 'RP2040 dual-core Cortex-M0+, 133MHz, 26 GPIO, 2MB flash, MicroPython support.',
    specifications: {'MCU': 'RP2040', 'Clock': '133 MHz', 'Flash': '2 MB', 'SRAM': '264 KB', 'GPIO': '26', 'Voltage': '3.3V'},
    price_inr: 499,
    price_usd: 6.0,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 630,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=RPi+Pico',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=Raspberry+Pi+Pico', 'Flipkart': 'https://www.flipkart.com/search?q=Raspberry+Pi+Pico', 'Robu.in': 'https://robu.in/?s=Raspberry+Pi+Pico'},
    alternatives: ['MCU-001', 'MCU-007'],
    tags: ['raspberry-pi', 'pico', 'rp2040', 'micropython'],
    manufacturer: 'Raspberry Pi Foundation',
    rating: 4.7,
    reviews: 18400,
  },
  {
    id: 'MCU-007',
    name: 'STM32 Blue Pill',
    part_number: 'STM32F103C8T6',
    category: 'Electrical',
    subcategory: 'Microcontrollers',
    description: 'ARM Cortex-M3, 72MHz, 64KB flash, 37 GPIO. Popular for advanced embedded projects.',
    specifications: {'MCU': 'STM32F103C8T6', 'Core': 'ARM Cortex-M3', 'Clock': '72 MHz', 'Flash': '64 KB', 'SRAM': '20 KB', 'GPIO': '37'},
    price_inr: 299,
    price_usd: 3.6,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 540,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=STM32',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=STM32+Blue+Pill', 'Flipkart': 'https://www.flipkart.com/search?q=STM32+Blue+Pill', 'Robu.in': 'https://robu.in/?s=STM32+Blue+Pill'},
    alternatives: ['MCU-006'],
    tags: ['stm32', 'arm', 'cortex-m3', 'embedded'],
    manufacturer: 'STMicroelectronics',
    rating: 4.3,
    reviews: 9800,
  },
  {
    id: 'MCU-008',
    name: 'Arduino Pro Mini 3.3V',
    part_number: 'DEV-11114',
    category: 'Electrical',
    subcategory: 'Microcontrollers',
    description: 'Minimalist ATmega328P at 3.3V/8MHz. No USB — for permanent low-power installations.',
    specifications: {'MCU': 'ATmega328P', 'Clock': '8 MHz', 'Voltage': '3.3V', 'Flash': '32 KB', 'GPIO': '14', 'Size': '18x33mm'},
    price_inr: 249,
    price_usd: 3.0,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 470,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=Pro+Mini',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=Arduino+Pro+Mini+3.3V', 'Flipkart': 'https://www.flipkart.com/search?q=Arduino+Pro+Mini+3.3V', 'Robu.in': 'https://robu.in/?s=Arduino+Pro+Mini+3.3V'},
    alternatives: ['MCU-004'],
    tags: ['arduino', 'pro-mini', 'low-power', 'compact'],
    manufacturer: 'Arduino',
    rating: 4.4,
    reviews: 8900,
  },
  {
    id: 'MCU-009',
    name: 'ATtiny85',
    part_number: 'ATTINY85-20PU',
    category: 'Electrical',
    subcategory: 'Microcontrollers',
    description: 'Ultra-compact 8-pin AVR, 6 I/O, 8KB flash. For minimal space-constrained projects.',
    specifications: {'MCU': 'ATtiny85', 'Clock': '8 MHz', 'Flash': '8 KB', 'I/O': '6', 'Voltage': '2.7-5.5V', 'Package': 'DIP-8'},
    price_inr: 149,
    price_usd: 1.8,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 890,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=ATtiny85',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=ATtiny85', 'Flipkart': 'https://www.flipkart.com/search?q=ATtiny85', 'Robu.in': 'https://robu.in/?s=ATtiny85'},
    alternatives: ['MCU-008'],
    tags: ['attiny85', 'avr', 'tiny', 'minimal'],
    manufacturer: 'Microchip',
    rating: 4.2,
    reviews: 6700,
  },
  {
    id: 'MCU-010',
    name: 'Raspberry Pi 4 Model B 4GB',
    part_number: 'SC0194',
    category: 'Electrical',
    subcategory: 'Single Board Computers',
    description: 'Quad-core 1.8GHz ARM Cortex-A72, 4GB RAM, dual 4K HDMI, USB 3.0, Gigabit Ethernet, WiFi+BT.',
    specifications: {'CPU': 'ARM Cortex-A72 Quad-core', 'Clock': '1.8 GHz', 'RAM': '4 GB LPDDR4', 'USB': '2x USB3.0 + 2x USB2.0', 'Display': '2x micro-HDMI 4K', 'Network': 'Gigabit + WiFi5 + BT5'},
    price_inr: 5499,
    price_usd: 66.3,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 45,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=RPi+4',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=Raspberry+Pi+4+4GB', 'Flipkart': 'https://www.flipkart.com/search?q=Raspberry+Pi+4+4GB', 'Robu.in': 'https://robu.in/?s=Raspberry+Pi+4+4GB'},
    alternatives: ['MCU-011'],
    tags: ['raspberry-pi', 'linux', 'sbc', 'ai', 'camera'],
    manufacturer: 'Raspberry Pi Foundation',
    rating: 4.8,
    reviews: 32000,
  },
  {
    id: 'MCU-011',
    name: 'Raspberry Pi 3 Model B+',
    part_number: 'SC0012',
    category: 'Electrical',
    subcategory: 'Single Board Computers',
    description: 'Quad-core 1.4GHz, 1GB RAM, WiFi, BT, 4x USB, HDMI. Great for home automation and media.',
    specifications: {'CPU': 'ARM Cortex-A53 Quad-core', 'Clock': '1.4 GHz', 'RAM': '1 GB', 'USB': '4x USB2.0', 'Network': 'WiFi + BT 4.2', 'GPIO': '40-pin'},
    price_inr: 3499,
    price_usd: 42.2,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 120,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=RPi+3B+',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=Raspberry+Pi+3+Model+B+', 'Flipkart': 'https://www.flipkart.com/search?q=Raspberry+Pi+3+Model+B+', 'Robu.in': 'https://robu.in/?s=Raspberry+Pi+3+Model+B+'},
    alternatives: ['MCU-010'],
    tags: ['raspberry-pi', 'linux', 'sbc', 'home-automation'],
    manufacturer: 'Raspberry Pi Foundation',
    rating: 4.7,
    reviews: 28000,
  },
  {
    id: 'MCU-012',
    name: 'Jetson Nano Developer Kit',
    part_number: '945-13450-0000-100',
    category: 'Electrical',
    subcategory: 'Single Board Computers',
    description: 'NVIDIA AI computing platform, 128-core Maxwell GPU, 4GB RAM, 4K video, for AI/ML edge projects.',
    specifications: {'GPU': '128-core Maxwell', 'CPU': 'Quad-core ARM A57', 'RAM': '4 GB LPDDR4', 'Storage': 'MicroSD', 'USB': '4x USB3.0', 'Camera': 'MIPI CSI-2'},
    price_inr: 8999,
    price_usd: 108.4,
    currency: 'INR',
    availability: 'limited',
    stock_qty: 28,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=Jetson+Nano',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=Jetson+Nano+Developer+Kit', 'Flipkart': 'https://www.flipkart.com/search?q=Jetson+Nano+Developer+Kit', 'Robu.in': 'https://robu.in/?s=Jetson+Nano+Developer+Kit'},
    alternatives: ['MCU-010'],
    tags: ['jetson', 'nvidia', 'ai', 'ml', 'gpu', 'edge-ai'],
    manufacturer: 'NVIDIA',
    rating: 4.7,
    reviews: 12000,
  },
  {
    id: 'SEN-001',
    name: 'DHT11 Temperature & Humidity Sensor',
    part_number: 'DHT11',
    category: 'Electrical',
    subcategory: 'Sensors',
    description: 'Digital temp+humidity sensor, 0-50°C / 20-90% RH, single-wire interface. Most popular beginner sensor.',
    specifications: {'Temp Range': '0-50°C', 'Humidity': '20-90% RH', 'Accuracy Temp': '±2°C', 'Accuracy RH': '±5%', 'Voltage': '3-5.5V', 'Interface': 'Single-wire'},
    price_inr: 119,
    price_usd: 1.4,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 600,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=DHT11',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=DHT11+Sensor', 'Flipkart': 'https://www.flipkart.com/search?q=DHT11+Sensor', 'Robu.in': 'https://robu.in/?s=DHT11+Sensor'},
    alternatives: ['SEN-002'],
    tags: ['dht11', 'temperature', 'humidity', 'sensor'],
    manufacturer: 'Aosong',
    rating: 4.3,
    reviews: 14200,
  },
  {
    id: 'SEN-002',
    name: 'DHT22 Temperature & Humidity Sensor',
    part_number: 'DHT22',
    category: 'Electrical',
    subcategory: 'Sensors',
    description: 'Higher accuracy temp+humidity sensor, -40 to 80°C, 0-100% RH. Better than DHT11 for precision.',
    specifications: {'Temp Range': '-40 to 80°C', 'Humidity': '0-100% RH', 'Accuracy Temp': '±0.5°C', 'Accuracy RH': '±2-5%', 'Voltage': '3.3-6V', 'Interface': 'Single-wire'},
    price_inr: 249,
    price_usd: 3.0,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 480,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=DHT22',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=DHT22+Sensor', 'Flipkart': 'https://www.flipkart.com/search?q=DHT22+Sensor', 'Robu.in': 'https://robu.in/?s=DHT22+Sensor'},
    alternatives: ['SEN-001'],
    tags: ['dht22', 'temperature', 'humidity', 'sensor', 'precision'],
    manufacturer: 'Aosong',
    rating: 4.6,
    reviews: 11800,
  },
  {
    id: 'SEN-003',
    name: 'HC-SR04 Ultrasonic Distance Sensor',
    part_number: 'HC-SR04',
    category: 'Electrical',
    subcategory: 'Sensors',
    description: 'Ultrasonic ranging module, 2-400cm range, 3mm accuracy, 5V, TTL output. Essential for robotics.',
    specifications: {'Range': '2-400 cm', 'Accuracy': '3 mm', 'Frequency': '40 kHz', 'Voltage': '5V', 'Trigger': '10µs TTL', 'Beam Angle': '15°'},
    price_inr: 89,
    price_usd: 1.1,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 680,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=HC-SR04',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=HC-SR04+Ultrasonic', 'Flipkart': 'https://www.flipkart.com/search?q=HC-SR04+Ultrasonic', 'Robu.in': 'https://robu.in/?s=HC-SR04+Ultrasonic'},
    alternatives: ['SEN-004'],
    tags: ['ultrasonic', 'distance', 'sensor', 'robot', 'hc-sr04'],
    manufacturer: 'Generic',
    rating: 4.5,
    reviews: 18900,
  },
  {
    id: 'SEN-004',
    name: 'VL53L0X ToF Distance Sensor',
    part_number: 'VL53L0X',
    category: 'Electrical',
    subcategory: 'Sensors',
    description: 'Time-of-Flight laser ranging sensor, up to 2m, I2C interface, 940nm VCSEL laser. More accurate than ultrasonic.',
    specifications: {'Range': 'Up to 2 m', 'Interface': 'I2C', 'Voltage': '2.6-3.5V', 'Accuracy': '±3%', 'Wavelength': '940 nm', 'Size': '4.4x2.4mm'},
    price_inr: 349,
    price_usd: 4.2,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 220,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=VL53L0X',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=VL53L0X+ToF+Sensor', 'Flipkart': 'https://www.flipkart.com/search?q=VL53L0X+ToF+Sensor', 'Robu.in': 'https://robu.in/?s=VL53L0X+ToF+Sensor'},
    alternatives: ['SEN-003'],
    tags: ['tof', 'laser', 'distance', 'sensor', 'i2c'],
    manufacturer: 'STMicroelectronics',
    rating: 4.5,
    reviews: 7800,
  },
  {
    id: 'SEN-005',
    name: 'Soil Moisture Sensor (Capacitive)',
    part_number: 'SEN-SOIL-CAP',
    category: 'Electrical',
    subcategory: 'Sensors',
    description: 'Corrosion-resistant capacitive soil moisture sensor, analog 0-3V output. Better than resistive type.',
    specifications: {'Output': 'Analog 0-3V', 'Voltage': '3.3-5.5V', 'Current': '5 mA', 'Length': '98 mm', 'Interface': 'Analog'},
    price_inr: 149,
    price_usd: 1.8,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 450,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=Soil+Sensor',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=Capacitive+Soil+Moisture+Sensor', 'Flipkart': 'https://www.flipkart.com/search?q=Capacitive+Soil+Moisture+Sensor', 'Robu.in': 'https://robu.in/?s=Capacitive+Soil+Moisture+Sensor'},
    alternatives: ['SEN-006'],
    tags: ['soil', 'moisture', 'sensor', 'agriculture', 'iot'],
    manufacturer: 'Generic',
    rating: 4.2,
    reviews: 3200,
  },
  {
    id: 'SEN-006',
    name: 'Resistive Soil Moisture Sensor',
    part_number: 'SEN-SOIL-RES',
    category: 'Electrical',
    subcategory: 'Sensors',
    description: 'Basic resistive soil moisture sensor with digital+analog output. Low cost for simple irrigation projects.',
    specifications: {'Output': 'Digital + Analog', 'Voltage': '3.3-5V', 'Probes': '2 electrodes', 'Interface': 'Analog/Digital'},
    price_inr: 59,
    price_usd: 0.7,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 820,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=Soil+Resistive',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=Soil+Moisture+Sensor+Module', 'Flipkart': 'https://www.flipkart.com/search?q=Soil+Moisture+Sensor+Module', 'Robu.in': 'https://robu.in/?s=Soil+Moisture+Sensor+Module'},
    alternatives: ['SEN-005'],
    tags: ['soil', 'moisture', 'sensor', 'agriculture', 'cheap'],
    manufacturer: 'Generic',
    rating: 3.9,
    reviews: 5600,
  },
  {
    id: 'SEN-007',
    name: 'PIR Motion Sensor HC-SR501',
    part_number: 'HC-SR501',
    category: 'Electrical',
    subcategory: 'Sensors',
    description: 'Passive infrared motion sensor, 3-7m range, 110° cone, adjustable sensitivity and delay time.',
    specifications: {'Range': '3-7 m', 'Angle': '110°', 'Voltage': '4.5-20V', 'Output': 'Digital 3.3V', 'Delay': '0.3-200s', 'Sensitivity': 'Adjustable'},
    price_inr: 79,
    price_usd: 1.0,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 520,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=PIR+Sensor',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=PIR+Motion+Sensor+HC-SR501', 'Flipkart': 'https://www.flipkart.com/search?q=PIR+Motion+Sensor+HC-SR501', 'Robu.in': 'https://robu.in/?s=PIR+Motion+Sensor+HC-SR501'},
    alternatives: ['SEN-008'],
    tags: ['pir', 'motion', 'sensor', 'security', 'iot'],
    manufacturer: 'Generic',
    rating: 4.4,
    reviews: 12600,
  },
  {
    id: 'SEN-008',
    name: 'RCWL-0516 Microwave Radar Sensor',
    part_number: 'RCWL-0516',
    category: 'Electrical',
    subcategory: 'Sensors',
    description: 'Microwave Doppler radar motion sensor, works through walls/glass, 5-7m range, 360° detection.',
    specifications: {'Range': '5-7 m', 'Detection': '360°', 'Voltage': '4-28V', 'Output': 'Digital 3.3V', 'Frequency': '3.18 GHz', 'Works Through': 'Walls/Glass'},
    price_inr: 99,
    price_usd: 1.2,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 310,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=RCWL',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=RCWL-0516+Microwave+Sensor', 'Flipkart': 'https://www.flipkart.com/search?q=RCWL-0516+Microwave+Sensor', 'Robu.in': 'https://robu.in/?s=RCWL-0516+Microwave+Sensor'},
    alternatives: ['SEN-007'],
    tags: ['microwave', 'radar', 'motion', 'sensor', 'security'],
    manufacturer: 'Generic',
    rating: 4.3,
    reviews: 4800,
  },
  {
    id: 'SEN-009',
    name: 'MPU-6050 Gyroscope + Accelerometer',
    part_number: 'MPU-6050',
    category: 'Electrical',
    subcategory: 'Sensors',
    description: '6-axis IMU with 3-axis gyroscope and 3-axis accelerometer, I2C/SPI, DMP for gesture recognition.',
    specifications: {'Axes': '6 (3-axis gyro + 3-axis accel)', 'Interface': 'I2C / SPI', 'Voltage': '3-5V', 'Gyro Range': '±250/500/1000/2000°/s', 'Accel Range': '±2/4/8/16g', 'DMP': 'Yes'},
    price_inr: 199,
    price_usd: 2.4,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 560,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=MPU6050',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=MPU6050+Gyroscope+Accelerometer', 'Flipkart': 'https://www.flipkart.com/search?q=MPU6050+Gyroscope+Accelerometer', 'Robu.in': 'https://robu.in/?s=MPU6050+Gyroscope+Accelerometer'},
    alternatives: ['SEN-010'],
    tags: ['mpu6050', 'gyroscope', 'accelerometer', 'imu', 'gesture'],
    manufacturer: 'InvenSense',
    rating: 4.4,
    reviews: 8900,
  },
  {
    id: 'SEN-010',
    name: 'ADXL345 Accelerometer',
    part_number: 'ADXL345',
    category: 'Electrical',
    subcategory: 'Sensors',
    description: '3-axis digital accelerometer, ±16g range, I2C/SPI, tap/double-tap detection, low power.',
    specifications: {'Axes': '3-axis', 'Interface': 'I2C / SPI', 'Voltage': '2-3.6V', 'Range': '±2/4/8/16g', 'Resolution': '13-bit', 'Features': 'Tap detection, freefall'},
    price_inr: 249,
    price_usd: 3.0,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 280,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=ADXL345',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=ADXL345+Accelerometer', 'Flipkart': 'https://www.flipkart.com/search?q=ADXL345+Accelerometer', 'Robu.in': 'https://robu.in/?s=ADXL345+Accelerometer'},
    alternatives: ['SEN-009'],
    tags: ['adxl345', 'accelerometer', '3-axis', 'i2c', 'spi'],
    manufacturer: 'Analog Devices',
    rating: 4.3,
    reviews: 5600,
  },
  {
    id: 'SEN-011',
    name: 'MQ-2 Gas/Smoke Sensor',
    part_number: 'MQ-2',
    category: 'Electrical',
    subcategory: 'Sensors',
    description: 'Detects LPG, smoke, alcohol, propane, hydrogen, methane. Analog+digital output. For fire/gas alarms.',
    specifications: {'Detects': 'LPG, Smoke, Alcohol, Propane, H2, CH4', 'Output': 'Analog + Digital', 'Voltage': '5V', 'Preheat': '20s', 'Sensitivity': 'Adjustable'},
    price_inr: 149,
    price_usd: 1.8,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 390,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=MQ-2',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=MQ-2+Gas+Sensor', 'Flipkart': 'https://www.flipkart.com/search?q=MQ-2+Gas+Sensor', 'Robu.in': 'https://robu.in/?s=MQ-2+Gas+Sensor'},
    alternatives: ['SEN-012'],
    tags: ['mq2', 'gas', 'smoke', 'sensor', 'fire', 'alarm'],
    manufacturer: 'Generic',
    rating: 4.1,
    reviews: 7200,
  },
  {
    id: 'SEN-012',
    name: 'MQ-3 Alcohol Sensor',
    part_number: 'MQ-3',
    category: 'Electrical',
    subcategory: 'Sensors',
    description: 'Detects alcohol/ethanol vapors, analog output. Used in breathalyzer and smart helmet projects.',
    specifications: {'Detects': 'Alcohol, Ethanol', 'Output': 'Analog + Digital', 'Voltage': '5V', 'Sensitivity': 'Adjustable'},
    price_inr: 149,
    price_usd: 1.8,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 280,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=MQ-3',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=MQ-3+Alcohol+Sensor', 'Flipkart': 'https://www.flipkart.com/search?q=MQ-3+Alcohol+Sensor', 'Robu.in': 'https://robu.in/?s=MQ-3+Alcohol+Sensor'},
    alternatives: ['SEN-011'],
    tags: ['mq3', 'alcohol', 'ethanol', 'sensor', 'breathalyzer'],
    manufacturer: 'Generic',
    rating: 4.0,
    reviews: 4100,
  },
  {
    id: 'SEN-013',
    name: 'MAX30100 Pulse Oximeter Sensor',
    part_number: 'MAX30100',
    category: 'Electrical',
    subcategory: 'Sensors',
    description: 'Integrated pulse oximetry and heart-rate monitor sensor, I2C, for wearable health monitoring.',
    specifications: {'Measures': 'SpO2 + Heart Rate', 'Interface': 'I2C', 'Voltage': '1.8V (logic) / 3.3V', 'LED': 'Red 660nm + IR 880nm', 'Resolution': '16-bit'},
    price_inr: 349,
    price_usd: 4.2,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 210,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=MAX30100',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=MAX30100+Pulse+Oximeter', 'Flipkart': 'https://www.flipkart.com/search?q=MAX30100+Pulse+Oximeter', 'Robu.in': 'https://robu.in/?s=MAX30100+Pulse+Oximeter'},
    alternatives: ['SEN-014'],
    tags: ['max30100', 'pulse', 'oximeter', 'heart-rate', 'health', 'wearable'],
    manufacturer: 'Maxim Integrated',
    rating: 4.2,
    reviews: 5800,
  },
  {
    id: 'SEN-014',
    name: 'DS18B20 Waterproof Temperature Sensor',
    part_number: 'DS18B20',
    category: 'Electrical',
    subcategory: 'Sensors',
    description: 'Waterproof digital temperature sensor, -55 to 125°C, 1-Wire protocol, 12-bit resolution.',
    specifications: {'Range': '-55 to 125°C', 'Accuracy': '±0.5°C', 'Interface': '1-Wire', 'Resolution': '9-12 bit', 'Voltage': '3-5.5V', 'Waterproof': 'Yes'},
    price_inr: 199,
    price_usd: 2.4,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 340,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=DS18B20',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=DS18B20+Waterproof+Temperature+Sensor', 'Flipkart': 'https://www.flipkart.com/search?q=DS18B20+Waterproof+Temperature+Sensor', 'Robu.in': 'https://robu.in/?s=DS18B20+Waterproof+Temperature+Sensor'},
    alternatives: ['SEN-001'],
    tags: ['ds18b20', 'temperature', 'waterproof', '1-wire', 'sensor'],
    manufacturer: 'Maxim Integrated',
    rating: 4.5,
    reviews: 9200,
  },
  {
    id: 'SEN-015',
    name: 'BMP280 Pressure & Temperature Sensor',
    part_number: 'BMP280',
    category: 'Electrical',
    subcategory: 'Sensors',
    description: 'Barometric pressure and temperature sensor, I2C/SPI, ±1 hPa accuracy. For weather stations and altitude.',
    specifications: {'Measures': 'Pressure + Temperature', 'Interface': 'I2C / SPI', 'Voltage': '1.71-3.6V', 'Pressure Range': '300-1100 hPa', 'Accuracy': '±1 hPa', 'Altitude': '±1 m'},
    price_inr: 199,
    price_usd: 2.4,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 380,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=BMP280',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=BMP280+Pressure+Sensor', 'Flipkart': 'https://www.flipkart.com/search?q=BMP280+Pressure+Sensor', 'Robu.in': 'https://robu.in/?s=BMP280+Pressure+Sensor'},
    alternatives: ['SEN-016'],
    tags: ['bmp280', 'pressure', 'temperature', 'barometric', 'weather', 'altitude'],
    manufacturer: 'Bosch',
    rating: 4.5,
    reviews: 8700,
  },
  {
    id: 'SEN-016',
    name: 'BME280 Temp/Humidity/Pressure Sensor',
    part_number: 'BME280',
    category: 'Electrical',
    subcategory: 'Sensors',
    description: 'All-in-one environmental sensor: temperature, humidity, and pressure. I2C/SPI. Best for weather stations.',
    specifications: {'Measures': 'Temp + Humidity + Pressure', 'Interface': 'I2C / SPI', 'Voltage': '1.71-3.6V', 'Temp Accuracy': '±0.5°C', 'Humidity Accuracy': '±3%'},
    price_inr: 299,
    price_usd: 3.6,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 290,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=BME280',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=BME280+Environmental+Sensor', 'Flipkart': 'https://www.flipkart.com/search?q=BME280+Environmental+Sensor', 'Robu.in': 'https://robu.in/?s=BME280+Environmental+Sensor'},
    alternatives: ['SEN-015', 'SEN-002'],
    tags: ['bme280', 'temperature', 'humidity', 'pressure', 'weather', 'all-in-one'],
    manufacturer: 'Bosch',
    rating: 4.7,
    reviews: 11200,
  },
  {
    id: 'SEN-017',
    name: 'IR Obstacle Avoidance Sensor',
    part_number: 'IR-OBS',
    category: 'Electrical',
    subcategory: 'Sensors',
    description: 'Adjustable IR obstacle detection, 2-30cm range, digital output, onboard LED. For line following robots.',
    specifications: {'Range': '2-30 cm', 'Output': 'Digital TTL', 'Voltage': '3.3-5V', 'Wavelength': '940 nm', 'Adjustment': 'Potentiometer'},
    price_inr: 59,
    price_usd: 0.7,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 750,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=IR+Sensor',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=IR+Obstacle+Avoidance+Sensor', 'Flipkart': 'https://www.flipkart.com/search?q=IR+Obstacle+Avoidance+Sensor', 'Robu.in': 'https://robu.in/?s=IR+Obstacle+Avoidance+Sensor'},
    alternatives: ['SEN-003'],
    tags: ['ir', 'infrared', 'obstacle', 'sensor', 'robot', 'line-following'],
    manufacturer: 'Generic',
    rating: 4.1,
    reviews: 5400,
  },
  {
    id: 'SEN-018',
    name: 'TCRT5000 Line Tracking Sensor',
    part_number: 'TCRT5000',
    category: 'Electrical',
    subcategory: 'Sensors',
    description: 'Reflective optical sensor for line tracking robots. Detects black/white lines, analog+digital output.',
    specifications: {'Output': 'Analog + Digital', 'Voltage': '3.3-5V', 'Detection': 'Black/White lines', 'Range': '0-25 mm'},
    price_inr: 49,
    price_usd: 0.6,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 620,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=TCRT5000',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=TCRT5000+Line+Tracking+Sensor', 'Flipkart': 'https://www.flipkart.com/search?q=TCRT5000+Line+Tracking+Sensor', 'Robu.in': 'https://robu.in/?s=TCRT5000+Line+Tracking+Sensor'},
    alternatives: ['SEN-017'],
    tags: ['tcrt5000', 'line-tracking', 'sensor', 'robot', 'optical'],
    manufacturer: 'Generic',
    rating: 4.2,
    reviews: 6800,
  },
  {
    id: 'SEN-019',
    name: 'MFRC522 RFID Reader Module',
    part_number: 'MFRC522',
    category: 'Electrical',
    subcategory: 'Sensors',
    description: '13.56MHz RFID reader/writer, SPI interface, includes RFID card and key fob. For access control projects.',
    specifications: {'Frequency': '13.56 MHz', 'Interface': 'SPI', 'Voltage': '3.3V', 'Range': 'Up to 5 cm', 'Includes': 'RFID card + key fob'},
    price_inr: 199,
    price_usd: 2.4,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 480,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=RFID',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=MFRC522+RFID+Module', 'Flipkart': 'https://www.flipkart.com/search?q=MFRC522+RFID+Module', 'Robu.in': 'https://robu.in/?s=MFRC522+RFID+Module'},
    alternatives: ['SEN-020'],
    tags: ['rfid', 'mfrc522', 'access-control', 'nfc', 'spi'],
    manufacturer: 'NXP',
    rating: 4.3,
    reviews: 11200,
  },
  {
    id: 'SEN-020',
    name: 'PN532 NFC Module',
    part_number: 'PN532',
    category: 'Electrical',
    subcategory: 'Sensors',
    description: 'NFC/RFID reader supporting ISO14443A/B, MIFARE, FeliCa. I2C/SPI/UART. For advanced NFC projects.',
    specifications: {'Frequency': '13.56 MHz', 'Interface': 'I2C / SPI / UART', 'Voltage': '3.3V', 'Protocols': 'ISO14443A/B, MIFARE, FeliCa'},
    price_inr: 499,
    price_usd: 6.0,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 140,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=PN532',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=PN532+NFC+Module', 'Flipkart': 'https://www.flipkart.com/search?q=PN532+NFC+Module', 'Robu.in': 'https://robu.in/?s=PN532+NFC+Module'},
    alternatives: ['SEN-019'],
    tags: ['nfc', 'pn532', 'rfid', 'i2c', 'spi'],
    manufacturer: 'NXP',
    rating: 4.4,
    reviews: 4200,
  },
  {
    id: 'SEN-021',
    name: 'NEO-6M GPS Module',
    part_number: 'NEO-6M',
    category: 'Electrical',
    subcategory: 'Sensors',
    description: 'GPS receiver module, UART interface, 3.3V, 1Hz update rate, -161dBm sensitivity. For tracking projects.',
    specifications: {'Protocol': 'NMEA 0183', 'Interface': 'UART', 'Voltage': '3.3V', 'Update Rate': '1 Hz', 'Sensitivity': '-161 dBm', 'Channels': '50'},
    price_inr: 599,
    price_usd: 7.2,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 180,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=GPS+NEO-6M',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=NEO-6M+GPS+Module', 'Flipkart': 'https://www.flipkart.com/search?q=NEO-6M+GPS+Module', 'Robu.in': 'https://robu.in/?s=NEO-6M+GPS+Module'},
    alternatives: ['SEN-022'],
    tags: ['gps', 'neo-6m', 'location', 'tracking', 'uart'],
    manufacturer: 'u-blox',
    rating: 4.3,
    reviews: 7600,
  },
  {
    id: 'SEN-022',
    name: 'SIM800L GSM/GPRS Module',
    part_number: 'SIM800L',
    category: 'Electrical',
    subcategory: 'Sensors',
    description: 'Quad-band GSM/GPRS module, UART, supports SMS/calls/data. For IoT remote monitoring and alerts.',
    specifications: {'Bands': '850/900/1800/1900 MHz', 'Interface': 'UART', 'Voltage': '3.4-4.4V', 'Features': 'SMS, Call, GPRS, HTTP'},
    price_inr: 699,
    price_usd: 8.4,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 150,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=SIM800L',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=SIM800L+GSM+Module', 'Flipkart': 'https://www.flipkart.com/search?q=SIM800L+GSM+Module', 'Robu.in': 'https://robu.in/?s=SIM800L+GSM+Module'},
    alternatives: ['SEN-021'],
    tags: ['gsm', 'gprs', 'sim800l', 'sms', 'iot', 'cellular'],
    manufacturer: 'SIMCom',
    rating: 4.1,
    reviews: 5900,
  },
  {
    id: 'SEN-023',
    name: 'Flame Sensor Module',
    part_number: 'FLAME-MOD',
    category: 'Electrical',
    subcategory: 'Sensors',
    description: 'Detects flame/fire using IR photodiode, 60cm range, analog+digital output. For fire alarm systems.',
    specifications: {'Detection': 'Flame/Fire', 'Range': 'Up to 60 cm', 'Output': 'Analog + Digital', 'Voltage': '3.3-5V', 'Wavelength': '760-1100 nm'},
    price_inr: 79,
    price_usd: 1.0,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 410,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=Flame+Sensor',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=Flame+Sensor+Module', 'Flipkart': 'https://www.flipkart.com/search?q=Flame+Sensor+Module', 'Robu.in': 'https://robu.in/?s=Flame+Sensor+Module'},
    alternatives: ['SEN-011'],
    tags: ['flame', 'fire', 'sensor', 'alarm', 'safety'],
    manufacturer: 'Generic',
    rating: 4.0,
    reviews: 4800,
  },
  {
    id: 'SEN-024',
    name: 'Rain/Water Level Sensor',
    part_number: 'RAIN-MOD',
    category: 'Electrical',
    subcategory: 'Sensors',
    description: 'Detects rain/water presence, analog+digital output, adjustable sensitivity. For weather monitoring.',
    specifications: {'Output': 'Analog + Digital', 'Voltage': '3.3-5V', 'Sensitivity': 'Adjustable', 'PCB Size': '5x4 cm'},
    price_inr: 79,
    price_usd: 1.0,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 360,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=Rain+Sensor',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=Rain+Sensor+Module', 'Flipkart': 'https://www.flipkart.com/search?q=Rain+Sensor+Module', 'Robu.in': 'https://robu.in/?s=Rain+Sensor+Module'},
    alternatives: ['SEN-016'],
    tags: ['rain', 'water', 'sensor', 'weather', 'detection'],
    manufacturer: 'Generic',
    rating: 3.9,
    reviews: 3900,
  },
  {
    id: 'SEN-025',
    name: 'LDR Light Sensor Module',
    part_number: 'LDR-MOD',
    category: 'Electrical',
    subcategory: 'Sensors',
    description: 'Light-dependent resistor module with digital comparator output. For automatic lighting and light detection.',
    specifications: {'Output': 'Analog + Digital', 'Voltage': '3.3-5V', 'Sensitivity': 'Adjustable', 'Response': 'Visible light'},
    price_inr: 49,
    price_usd: 0.6,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 680,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=LDR',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=LDR+Light+Sensor+Module', 'Flipkart': 'https://www.flipkart.com/search?q=LDR+Light+Sensor+Module', 'Robu.in': 'https://robu.in/?s=LDR+Light+Sensor+Module'},
    alternatives: ['SEN-025'],
    tags: ['ldr', 'light', 'sensor', 'photoresistor', 'automatic-lighting'],
    manufacturer: 'Generic',
    rating: 4.1,
    reviews: 7200,
  },
  {
    id: 'SEN-026',
    name: 'Sound/Microphone Sensor Module',
    part_number: 'SOUND-MOD',
    category: 'Electrical',
    subcategory: 'Sensors',
    description: 'Electret microphone with LM393 comparator, analog+digital output, adjustable sensitivity.',
    specifications: {'Output': 'Analog + Digital', 'Voltage': '3.3-5V', 'Sensitivity': 'Adjustable', 'Microphone': 'Electret'},
    price_inr: 79,
    price_usd: 1.0,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 420,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=Sound+Sensor',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=Sound+Sensor+Module', 'Flipkart': 'https://www.flipkart.com/search?q=Sound+Sensor+Module', 'Robu.in': 'https://robu.in/?s=Sound+Sensor+Module'},
    alternatives: ['SEN-026'],
    tags: ['sound', 'microphone', 'sensor', 'audio', 'detection'],
    manufacturer: 'Generic',
    rating: 4.0,
    reviews: 5100,
  },
  {
    id: 'DIS-001',
    name: '0.96" OLED Display I2C (128x64)',
    part_number: 'SSD1306-096',
    category: 'Electrical',
    subcategory: 'Displays',
    description: 'Compact OLED display, 128x64 pixels, I2C, 3.3-5V. Perfect for showing sensor data in projects.',
    specifications: {'Resolution': '128x64 pixels', 'Interface': 'I2C (SDA/SCL)', 'Voltage': '3.3-5V', 'Driver': 'SSD1306', 'Size': '0.96 inch', 'Color': 'White/Blue/Yellow'},
    price_inr: 199,
    price_usd: 2.4,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 720,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=OLED+0.96',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=0.96+OLED+Display+I2C', 'Flipkart': 'https://www.flipkart.com/search?q=0.96+OLED+Display+I2C', 'Robu.in': 'https://robu.in/?s=0.96+OLED+Display+I2C'},
    alternatives: ['DIS-002'],
    tags: ['oled', 'display', 'ssd1306', 'i2c', '128x64'],
    manufacturer: 'Generic',
    rating: 4.5,
    reviews: 14500,
  },
  {
    id: 'DIS-002',
    name: '1.3" OLED Display I2C (128x64)',
    part_number: 'SH1106-13',
    category: 'Electrical',
    subcategory: 'Displays',
    description: 'Larger OLED display, 128x64 pixels, I2C, SH1106 driver. Better viewing angle than 0.96" version.',
    specifications: {'Resolution': '128x64 pixels', 'Interface': 'I2C', 'Voltage': '3.3-5V', 'Driver': 'SH1106', 'Size': '1.3 inch', 'Color': 'White'},
    price_inr: 249,
    price_usd: 3.0,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 380,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=OLED+1.3',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=1.3+OLED+Display+I2C', 'Flipkart': 'https://www.flipkart.com/search?q=1.3+OLED+Display+I2C', 'Robu.in': 'https://robu.in/?s=1.3+OLED+Display+I2C'},
    alternatives: ['DIS-001'],
    tags: ['oled', 'display', 'sh1106', 'i2c', '1.3inch'],
    manufacturer: 'Generic',
    rating: 4.4,
    reviews: 7800,
  },
  {
    id: 'DIS-003',
    name: '16x2 LCD Display with I2C Backpack',
    part_number: 'LCD-16X2-I2C',
    category: 'Electrical',
    subcategory: 'Displays',
    description: '16 character x 2 line LCD with I2C adapter. Only 2 wires needed (SDA/SCL). Blue/green backlight.',
    specifications: {'Characters': '16x2', 'Interface': 'I2C (via PCF8574)', 'Voltage': '5V', 'Backlight': 'Blue/Green', 'Contrast': 'Adjustable'},
    price_inr: 199,
    price_usd: 2.4,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 560,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=LCD+16x2',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=16x2+LCD+I2C+Display', 'Flipkart': 'https://www.flipkart.com/search?q=16x2+LCD+I2C+Display', 'Robu.in': 'https://robu.in/?s=16x2+LCD+I2C+Display'},
    alternatives: ['DIS-004'],
    tags: ['lcd', '16x2', 'i2c', 'display', 'characters'],
    manufacturer: 'Generic',
    rating: 4.3,
    reviews: 12800,
  },
  {
    id: 'DIS-004',
    name: '20x4 LCD Display with I2C',
    part_number: 'LCD-20X4-I2C',
    category: 'Electrical',
    subcategory: 'Displays',
    description: '20 character x 4 line LCD with I2C adapter. More display area for complex data output.',
    specifications: {'Characters': '20x4', 'Interface': 'I2C', 'Voltage': '5V', 'Backlight': 'Blue', 'Contrast': 'Adjustable'},
    price_inr: 299,
    price_usd: 3.6,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 280,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=LCD+20x4',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=20x4+LCD+I2C+Display', 'Flipkart': 'https://www.flipkart.com/search?q=20x4+LCD+I2C+Display', 'Robu.in': 'https://robu.in/?s=20x4+LCD+I2C+Display'},
    alternatives: ['DIS-003'],
    tags: ['lcd', '20x4', 'i2c', 'display', 'characters'],
    manufacturer: 'Generic',
    rating: 4.3,
    reviews: 6200,
  },
  {
    id: 'DIS-005',
    name: '2.4" TFT LCD Touchscreen (ILI9341)',
    part_number: 'ILI9341-24',
    category: 'Electrical',
    subcategory: 'Displays',
    description: '240x320 color TFT LCD with resistive touchscreen, SPI interface. For graphical UI projects.',
    specifications: {'Resolution': '240x320 pixels', 'Interface': 'SPI', 'Voltage': '3.3V', 'Driver': 'ILI9341', 'Touch': 'Resistive', 'Colors': '65K'},
    price_inr: 499,
    price_usd: 6.0,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 190,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=TFT+2.4',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=2.4+TFT+LCD+Touchscreen', 'Flipkart': 'https://www.flipkart.com/search?q=2.4+TFT+LCD+Touchscreen', 'Robu.in': 'https://robu.in/?s=2.4+TFT+LCD+Touchscreen'},
    alternatives: ['DIS-006'],
    tags: ['tft', 'lcd', 'touchscreen', 'ili9341', 'spi', 'color'],
    manufacturer: 'Generic',
    rating: 4.2,
    reviews: 5400,
  },
  {
    id: 'DIS-006',
    name: '3.5" TFT LCD Touchscreen (ILI9486)',
    part_number: 'ILI9486-35',
    category: 'Electrical',
    subcategory: 'Displays',
    description: '480x320 color TFT LCD with resistive touch, Arduino Mega shield compatible.',
    specifications: {'Resolution': '480x320 pixels', 'Interface': 'SPI / Parallel', 'Voltage': '3.3-5V', 'Driver': 'ILI9486', 'Touch': 'Resistive'},
    price_inr: 799,
    price_usd: 9.6,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 120,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=TFT+3.5',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=3.5+TFT+LCD+Touchscreen', 'Flipkart': 'https://www.flipkart.com/search?q=3.5+TFT+LCD+Touchscreen', 'Robu.in': 'https://robu.in/?s=3.5+TFT+LCD+Touchscreen'},
    alternatives: ['DIS-005'],
    tags: ['tft', 'lcd', 'touchscreen', 'ili9486', 'color', 'shield'],
    manufacturer: 'Generic',
    rating: 4.1,
    reviews: 3800,
  },
  {
    id: 'DIS-007',
    name: 'MAX7219 8x8 LED Matrix Module',
    part_number: 'MAX7219-8X8',
    category: 'Electrical',
    subcategory: 'Displays',
    description: '8x8 LED dot matrix display with MAX7219 driver, SPI interface, chainable for larger displays.',
    specifications: {'LEDs': '8x8 = 64', 'Interface': 'SPI', 'Voltage': '5V', 'Driver': 'MAX7219', 'Chainable': 'Yes'},
    price_inr: 149,
    price_usd: 1.8,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 440,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=LED+Matrix',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=MAX7219+LED+Matrix+Module', 'Flipkart': 'https://www.flipkart.com/search?q=MAX7219+LED+Matrix+Module', 'Robu.in': 'https://robu.in/?s=MAX7219+LED+Matrix+Module'},
    alternatives: ['DIS-001'],
    tags: ['led-matrix', 'max7219', '8x8', 'spi', 'display'],
    manufacturer: 'Generic',
    rating: 4.3,
    reviews: 8900,
  },
  {
    id: 'DIS-008',
    name: '7-Segment Display (4-digit)',
    part_number: '7SEG-4D',
    category: 'Electrical',
    subcategory: 'Displays',
    description: '4-digit 7-segment LED display with TM1637 driver, I2C-like interface, for clocks and counters.',
    specifications: {'Digits': '4', 'Interface': 'TM1637 (2-wire)', 'Voltage': '3.3-5V', 'Color': 'Red', 'Brightness': 'Adjustable'},
    price_inr: 149,
    price_usd: 1.8,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 380,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=7-Segment',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=4-digit+7-Segment+Display+TM1637', 'Flipkart': 'https://www.flipkart.com/search?q=4-digit+7-Segment+Display+TM1637', 'Robu.in': 'https://robu.in/?s=4-digit+7-Segment+Display+TM1637'},
    alternatives: ['DIS-003'],
    tags: ['7-segment', 'display', 'tm1637', 'clock', 'counter'],
    manufacturer: 'Generic',
    rating: 4.2,
    reviews: 7100,
  },
  {
    id: 'ACT-001',
    name: 'L298N Dual H-Bridge Motor Driver',
    part_number: 'L298N-MOD',
    category: 'Electrical',
    subcategory: 'Motor Drivers',
    description: 'Drives 2 DC motors or 1 stepper, 2A/channel, 5-35V. The most popular robot motor driver.',
    specifications: {'Driver IC': 'L298N', 'Max Voltage': '35V', 'Max Current': '2A per channel', 'Logic Voltage': '5V', 'Channels': '2 DC / 1 Stepper'},
    price_inr: 149,
    price_usd: 1.8,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 420,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=L298N',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=L298N+Motor+Driver+Module', 'Flipkart': 'https://www.flipkart.com/search?q=L298N+Motor+Driver+Module', 'Robu.in': 'https://robu.in/?s=L298N+Motor+Driver+Module'},
    alternatives: ['ACT-002'],
    tags: ['l298n', 'motor-driver', 'h-bridge', 'robot', 'dc-motor'],
    manufacturer: 'STMicroelectronics',
    rating: 4.3,
    reviews: 7600,
  },
  {
    id: 'ACT-002',
    name: 'L293D Motor Driver IC',
    part_number: 'L293D',
    category: 'Electrical',
    subcategory: 'Motor Drivers',
    description: 'Quad half-H driver IC, 600mA per channel, 4.5-36V. Compact DIP-16 package for PCB integration.',
    specifications: {'Driver IC': 'L293D', 'Max Voltage': '36V', 'Max Current': '600mA per channel', 'Channels': '4 (2 full H-bridges)', 'Package': 'DIP-16'},
    price_inr: 79,
    price_usd: 1.0,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 580,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=L293D',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=L293D+Motor+Driver+IC', 'Flipkart': 'https://www.flipkart.com/search?q=L293D+Motor+Driver+IC', 'Robu.in': 'https://robu.in/?s=L293D+Motor+Driver+IC'},
    alternatives: ['ACT-001'],
    tags: ['l293d', 'motor-driver', 'h-bridge', 'ic', 'dip16'],
    manufacturer: 'Texas Instruments',
    rating: 4.1,
    reviews: 5800,
  },
  {
    id: 'ACT-003',
    name: 'TB6612FNG Motor Driver Module',
    part_number: 'TB6612FNG',
    category: 'Electrical',
    subcategory: 'Motor Drivers',
    description: 'Dual DC motor driver, 1.2A/channel, 2.5-13.5V, PWM control. More efficient than L298N.',
    specifications: {'Driver IC': 'TB6612FNG', 'Max Voltage': '13.5V', 'Max Current': '1.2A per channel', 'Logic Voltage': '2.7-5.5V', 'Efficiency': 'High'},
    price_inr: 199,
    price_usd: 2.4,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 240,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=TB6612',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=TB6612FNG+Motor+Driver', 'Flipkart': 'https://www.flipkart.com/search?q=TB6612FNG+Motor+Driver', 'Robu.in': 'https://robu.in/?s=TB6612FNG+Motor+Driver'},
    alternatives: ['ACT-001'],
    tags: ['tb6612', 'motor-driver', 'efficient', 'pwm', 'robot'],
    manufacturer: 'Toshiba',
    rating: 4.5,
    reviews: 4200,
  },
  {
    id: 'ACT-004',
    name: 'A4988 Stepper Motor Driver',
    part_number: 'A4988',
    category: 'Electrical',
    subcategory: 'Motor Drivers',
    description: 'Microstepping stepper motor driver, up to 1/16 step, 2A max, for 3D printers and CNC machines.',
    specifications: {'Driver IC': 'A4988', 'Max Current': '2A', 'Microstepping': 'Full/Half/1/4/1/8/1/16', 'Voltage': '8-35V', 'Interface': 'Step/Dir'},
    price_inr: 149,
    price_usd: 1.8,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 320,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=A4988',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=A4988+Stepper+Motor+Driver', 'Flipkart': 'https://www.flipkart.com/search?q=A4988+Stepper+Motor+Driver', 'Robu.in': 'https://robu.in/?s=A4988+Stepper+Motor+Driver'},
    alternatives: ['ACT-005'],
    tags: ['a4988', 'stepper', 'motor-driver', '3d-printer', 'cnc'],
    manufacturer: 'Allegro',
    rating: 4.4,
    reviews: 9800,
  },
  {
    id: 'ACT-005',
    name: 'DRV8825 Stepper Motor Driver',
    part_number: 'DRV8825',
    category: 'Electrical',
    subcategory: 'Motor Drivers',
    description: 'Higher current stepper driver than A4988, up to 2.5A, 1/32 microstepping, for 3D printers.',
    specifications: {'Driver IC': 'DRV8825', 'Max Current': '2.5A', 'Microstepping': 'Up to 1/32', 'Voltage': '8.2-45V', 'Interface': 'Step/Dir'},
    price_inr: 179,
    price_usd: 2.2,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 280,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=DRV8825',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=DRV8825+Stepper+Motor+Driver', 'Flipkart': 'https://www.flipkart.com/search?q=DRV8825+Stepper+Motor+Driver', 'Robu.in': 'https://robu.in/?s=DRV8825+Stepper+Motor+Driver'},
    alternatives: ['ACT-004'],
    tags: ['drv8825', 'stepper', 'motor-driver', '3d-printer', 'high-current'],
    manufacturer: 'Texas Instruments',
    rating: 4.4,
    reviews: 7200,
  },
  {
    id: 'ACT-006',
    name: 'SG90 Micro Servo Motor',
    part_number: 'SG90',
    category: 'Mechanical',
    subcategory: 'Servos',
    description: '9g micro servo, 180° rotation, 1.8kgcm torque, PWM control. Most popular servo for beginners.',
    specifications: {'Torque': '1.8 kgcm at 4.8V', 'Speed': '0.1s/60° at 4.8V', 'Rotation': '0-180°', 'Control': 'PWM 50Hz', 'Weight': '9g', 'Voltage': '4.8-6V'},
    price_inr: 129,
    price_usd: 1.6,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 380,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=SG90',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=SG90+Servo+Motor', 'Flipkart': 'https://www.flipkart.com/search?q=SG90+Servo+Motor', 'Robu.in': 'https://robu.in/?s=SG90+Servo+Motor'},
    alternatives: ['ACT-007'],
    tags: ['sg90', 'servo', 'motor', 'pwm', 'robot', '9g'],
    manufacturer: 'Tower Pro',
    rating: 4.3,
    reviews: 9800,
  },
  {
    id: 'ACT-007',
    name: 'MG996R Metal Gear Servo',
    part_number: 'MG996R',
    category: 'Mechanical',
    subcategory: 'Servos',
    description: 'High-torque metal gear servo, 9.4kgcm, 180° rotation. For heavy-duty robotic arms and steering.',
    specifications: {'Torque': '9.4 kgcm at 4.8V', 'Speed': '0.17s/60° at 4.8V', 'Rotation': '0-180°', 'Gears': 'Metal', 'Weight': '55g', 'Voltage': '4.8-7.2V'},
    price_inr: 349,
    price_usd: 4.2,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 220,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=MG996R',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=MG996R+Servo+Motor', 'Flipkart': 'https://www.flipkart.com/search?q=MG996R+Servo+Motor', 'Robu.in': 'https://robu.in/?s=MG996R+Servo+Motor'},
    alternatives: ['ACT-006'],
    tags: ['mg996r', 'servo', 'metal-gear', 'high-torque', 'robot'],
    manufacturer: 'Tower Pro',
    rating: 4.4,
    reviews: 7600,
  },
  {
    id: 'ACT-008',
    name: '28BYJ-48 Stepper Motor + ULN2003 Driver',
    part_number: '28BYJ-48',
    category: 'Mechanical',
    subcategory: 'Stepper Motors',
    description: '5V unipolar stepper motor with ULN2003 driver board. 64 steps/rev, great for precise positioning.',
    specifications: {'Steps': '64 per revolution', 'Voltage': '5V', 'Reduction Ratio': '1/64', 'Torque': '34.3 mNm', 'Driver': 'ULN2003'},
    price_inr: 149,
    price_usd: 1.8,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 490,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=28BYJ-48',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=28BYJ-48+Stepper+Motor+ULN2003', 'Flipkart': 'https://www.flipkart.com/search?q=28BYJ-48+Stepper+Motor+ULN2003', 'Robu.in': 'https://robu.in/?s=28BYJ-48+Stepper+Motor+ULN2003'},
    alternatives: ['ACT-004'],
    tags: ['stepper', '28byj-48', 'uln2003', 'motor', 'precise'],
    manufacturer: 'Generic',
    rating: 4.2,
    reviews: 8400,
  },
  {
    id: 'ACT-009',
    name: 'DC Gear Motor 6V 200RPM',
    part_number: 'GM-6V-200',
    category: 'Mechanical',
    subcategory: 'DC Motors',
    description: 'Metal gearbox DC motor, 6V, 200RPM, 0.8kgcm torque. Standard motor for 2WD/4WD robot chassis.',
    specifications: {'Voltage': '6V DC', 'Speed': '200 RPM', 'Torque': '0.8 kgcm', 'Current': '60mA no-load', 'Shaft': '3mm D-shape'},
    price_inr: 179,
    price_usd: 2.2,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 220,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=DC+Motor',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=DC+Gear+Motor+6V+200RPM', 'Flipkart': 'https://www.flipkart.com/search?q=DC+Gear+Motor+6V+200RPM', 'Robu.in': 'https://robu.in/?s=DC+Gear+Motor+6V+200RPM'},
    alternatives: ['ACT-010'],
    tags: ['dc-motor', 'gear', 'robot', '6v', '200rpm'],
    manufacturer: 'Generic',
    rating: 4.2,
    reviews: 4100,
  },
  {
    id: 'ACT-010',
    name: 'N20 Micro Gear Motor 6V 100RPM',
    part_number: 'N20-6V-100',
    category: 'Mechanical',
    subcategory: 'DC Motors',
    description: 'Ultra-compact N20 micro gear motor, 6V, 100RPM. For small robots and precision mechanisms.',
    specifications: {'Voltage': '6V DC', 'Speed': '100 RPM', 'Torque': '0.6 kgcm', 'Size': '12x10x25mm', 'Shaft': '3mm'},
    price_inr: 249,
    price_usd: 3.0,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 180,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=N20+Motor',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=N20+Micro+Gear+Motor', 'Flipkart': 'https://www.flipkart.com/search?q=N20+Micro+Gear+Motor', 'Robu.in': 'https://robu.in/?s=N20+Micro+Gear+Motor'},
    alternatives: ['ACT-009'],
    tags: ['n20', 'micro-motor', 'gear', 'compact', 'robot'],
    manufacturer: 'Generic',
    rating: 4.3,
    reviews: 3200,
  },
  {
    id: 'ACT-011',
    name: '5V Single Channel Relay Module',
    part_number: 'REL-5V-1CH',
    category: 'Electrical',
    subcategory: 'Relays',
    description: 'Optocoupler-isolated relay, 10A/250VAC, active-low trigger. For controlling AC appliances.',
    specifications: {'Coil Voltage': '5V DC', 'Contact Rating': '10A 250VAC', 'Trigger': 'Active Low', 'Isolation': 'Optocoupler', 'Indicator': 'LED'},
    price_inr: 89,
    price_usd: 1.1,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 800,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=Relay+1CH',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=5V+Single+Channel+Relay+Module', 'Flipkart': 'https://www.flipkart.com/search?q=5V+Single+Channel+Relay+Module', 'Robu.in': 'https://robu.in/?s=5V+Single+Channel+Relay+Module'},
    alternatives: ['ACT-012'],
    tags: ['relay', '5v', 'switching', 'ac', 'optocoupler'],
    manufacturer: 'Generic',
    rating: 4.1,
    reviews: 6700,
  },
  {
    id: 'ACT-012',
    name: '4-Channel Relay Module 5V',
    part_number: 'REL-5V-4CH',
    category: 'Electrical',
    subcategory: 'Relays',
    description: '4 independent relays, 10A/250VAC each, optocoupler isolated. For home automation projects.',
    specifications: {'Coil Voltage': '5V DC', 'Channels': '4', 'Contact Rating': '10A 250VAC', 'Trigger': 'Active Low', 'Isolation': 'Optocoupler'},
    price_inr: 199,
    price_usd: 2.4,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 450,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=Relay+4CH',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=4+Channel+Relay+Module+5V', 'Flipkart': 'https://www.flipkart.com/search?q=4+Channel+Relay+Module+5V', 'Robu.in': 'https://robu.in/?s=4+Channel+Relay+Module+5V'},
    alternatives: ['ACT-011'],
    tags: ['relay', '4-channel', 'home-automation', 'ac', 'switching'],
    manufacturer: 'Generic',
    rating: 4.2,
    reviews: 9800,
  },
  {
    id: 'ACT-013',
    name: 'Mini Submersible Water Pump 3-6V',
    part_number: 'PUMP-3V',
    category: 'Mechanical',
    subcategory: 'Pumps',
    description: 'DC submersible pump, 3-6V, 80-120L/H flow rate. For irrigation and fountain projects.',
    specifications: {'Voltage': '3-6V DC', 'Flow Rate': '80-120 L/H', 'Max Head': '40-110 cm', 'Current': '130-220mA', 'Outlet': '7.5mm'},
    price_inr: 199,
    price_usd: 2.4,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 150,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=Water+Pump',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=Mini+Submersible+Water+Pump', 'Flipkart': 'https://www.flipkart.com/search?q=Mini+Submersible+Water+Pump', 'Robu.in': 'https://robu.in/?s=Mini+Submersible+Water+Pump'},
    alternatives: ['ACT-011'],
    tags: ['pump', 'water', 'submersible', 'irrigation', 'fountain'],
    manufacturer: 'Generic',
    rating: 4.0,
    reviews: 2800,
  },
  {
    id: 'ACT-014',
    name: 'Buzzer Active 5V',
    part_number: 'BUZZ-5V',
    category: 'Electrical',
    subcategory: 'Actuators',
    description: 'Active piezo buzzer, 5V, 85dB, 2.3kHz. Produces sound without external oscillator. For alarms.',
    specifications: {'Voltage': '5V DC', 'Sound Level': '85 dB', 'Frequency': '2.3 kHz', 'Type': 'Active (built-in oscillator)', 'Size': '12mm'},
    price_inr: 29,
    price_usd: 0.3,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 1200,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=Buzzer',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=Active+Buzzer+5V', 'Flipkart': 'https://www.flipkart.com/search?q=Active+Buzzer+5V', 'Robu.in': 'https://robu.in/?s=Active+Buzzer+5V'},
    alternatives: ['ACT-014'],
    tags: ['buzzer', 'active', 'piezo', 'alarm', 'sound'],
    manufacturer: 'Generic',
    rating: 4.0,
    reviews: 8900,
  },
  {
    id: 'ACT-015',
    name: 'Passive Buzzer Module',
    part_number: 'BUZZ-PASS',
    category: 'Electrical',
    subcategory: 'Actuators',
    description: 'Passive piezo buzzer module, requires PWM signal, can produce different tones/melodies.',
    specifications: {'Voltage': '3.3-5V', 'Type': 'Passive (needs PWM)', 'Tones': 'Variable frequency', 'Size': '12mm'},
    price_inr: 39,
    price_usd: 0.5,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 980,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=Passive+Buzzer',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=Passive+Buzzer+Module', 'Flipkart': 'https://www.flipkart.com/search?q=Passive+Buzzer+Module', 'Robu.in': 'https://robu.in/?s=Passive+Buzzer+Module'},
    alternatives: ['ACT-014'],
    tags: ['buzzer', 'passive', 'piezo', 'pwm', 'tones', 'music'],
    manufacturer: 'Generic',
    rating: 4.1,
    reviews: 6200,
  },
  {
    id: 'COM-001',
    name: 'nRF24L01+ 2.4GHz RF Module',
    part_number: 'NRF24L01',
    category: 'Electrical',
    subcategory: 'Wireless',
    description: '2.4GHz wireless transceiver, 250kbps-2Mbps, SPI, 100m range. For wireless robot control.',
    specifications: {'Frequency': '2.4 GHz', 'Data Rate': '250kbps / 1Mbps / 2Mbps', 'Range': 'Up to 100m', 'Interface': 'SPI', 'Voltage': '1.9-3.6V', 'Channels': '125'},
    price_inr: 149,
    price_usd: 1.8,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 380,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=nRF24L01',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=nRF24L01+RF+Module', 'Flipkart': 'https://www.flipkart.com/search?q=nRF24L01+RF+Module', 'Robu.in': 'https://robu.in/?s=nRF24L01+RF+Module'},
    alternatives: ['COM-002'],
    tags: ['nrf24l01', 'wireless', '2.4ghz', 'rf', 'spi', 'robot'],
    manufacturer: 'Nordic Semi',
    rating: 4.2,
    reviews: 7800,
  },
  {
    id: 'COM-002',
    name: 'HC-05 Bluetooth Module',
    part_number: 'HC-05',
    category: 'Electrical',
    subcategory: 'Wireless',
    description: 'Classic Bluetooth 2.0 module, UART, master/slave mode, 10m range. For wireless serial communication.',
    specifications: {'Protocol': 'Bluetooth 2.0', 'Interface': 'UART', 'Voltage': '3.3V (5V tolerant)', 'Range': 'Up to 10m', 'Mode': 'Master/Slave', 'Baud Rate': '9600 default'},
    price_inr: 299,
    price_usd: 3.6,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 420,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=HC-05',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=HC-05+Bluetooth+Module', 'Flipkart': 'https://www.flipkart.com/search?q=HC-05+Bluetooth+Module', 'Robu.in': 'https://robu.in/?s=HC-05+Bluetooth+Module'},
    alternatives: ['COM-003'],
    tags: ['hc-05', 'bluetooth', 'uart', 'wireless', 'serial'],
    manufacturer: 'Generic',
    rating: 4.3,
    reviews: 11200,
  },
  {
    id: 'COM-003',
    name: 'HC-06 Bluetooth Module (Slave)',
    part_number: 'HC-06',
    category: 'Electrical',
    subcategory: 'Wireless',
    description: 'Bluetooth 2.0 slave-only module, UART, simpler than HC-05. For connecting Arduino to smartphone.',
    specifications: {'Protocol': 'Bluetooth 2.0', 'Interface': 'UART', 'Voltage': '3.3V (5V tolerant)', 'Range': 'Up to 10m', 'Mode': 'Slave only'},
    price_inr: 249,
    price_usd: 3.0,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 360,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=HC-06',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=HC-06+Bluetooth+Module', 'Flipkart': 'https://www.flipkart.com/search?q=HC-06+Bluetooth+Module', 'Robu.in': 'https://robu.in/?s=HC-06+Bluetooth+Module'},
    alternatives: ['COM-002'],
    tags: ['hc-06', 'bluetooth', 'uart', 'wireless', 'slave'],
    manufacturer: 'Generic',
    rating: 4.2,
    reviews: 8900,
  },
  {
    id: 'COM-004',
    name: 'LoRa SX1278 433MHz Module',
    part_number: 'SX1278',
    category: 'Electrical',
    subcategory: 'Wireless',
    description: 'Long-range LoRa module, 433MHz, up to 10km range, SPI. For IoT sensor networks and remote monitoring.',
    specifications: {'Frequency': '433 MHz', 'Range': 'Up to 10 km', 'Interface': 'SPI', 'Voltage': '3.3V', 'Modulation': 'LoRa / FSK', 'Sensitivity': '-148 dBm'},
    price_inr: 599,
    price_usd: 7.2,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 140,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=LoRa',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=LoRa+SX1278+433MHz+Module', 'Flipkart': 'https://www.flipkart.com/search?q=LoRa+SX1278+433MHz+Module', 'Robu.in': 'https://robu.in/?s=LoRa+SX1278+433MHz+Module'},
    alternatives: ['COM-001'],
    tags: ['lora', 'sx1278', '433mhz', 'long-range', 'iot', 'lpwan'],
    manufacturer: 'Semtech',
    rating: 4.4,
    reviews: 4800,
  },
  {
    id: 'COM-005',
    name: '433MHz RF Transmitter + Receiver',
    part_number: 'RF-433',
    category: 'Electrical',
    subcategory: 'Wireless',
    description: 'Simple 433MHz RF pair, up to 100m range, ASK modulation. For basic wireless remote control.',
    specifications: {'Frequency': '433 MHz', 'Range': 'Up to 100m', 'Modulation': 'ASK', 'Voltage': 'TX: 3-12V, RX: 5V', 'Data Rate': 'Up to 10kbps'},
    price_inr: 99,
    price_usd: 1.2,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 560,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=RF+433',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=433MHz+RF+Transmitter+Receiver', 'Flipkart': 'https://www.flipkart.com/search?q=433MHz+RF+Transmitter+Receiver', 'Robu.in': 'https://robu.in/?s=433MHz+RF+Transmitter+Receiver'},
    alternatives: ['COM-001'],
    tags: ['rf', '433mhz', 'wireless', 'remote', 'transmitter', 'receiver'],
    manufacturer: 'Generic',
    rating: 3.9,
    reviews: 6200,
  },
  {
    id: 'COM-006',
    name: 'I2C Level Shifter (4-channel)',
    part_number: 'I2C-LEVEL',
    category: 'Electrical',
    subcategory: 'Interface',
    description: 'Bidirectional I2C/SPI level shifter, 3.3V ↔ 5V, 4 channels. Essential for mixing 3.3V and 5V devices.',
    specifications: {'Channels': '4', 'Voltage': '3.3V ↔ 5V', 'Interface': 'I2C / SPI / UART', 'Direction': 'Bidirectional'},
    price_inr: 99,
    price_usd: 1.2,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 380,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=Level+Shifter',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=I2C+Level+Shifter+4+Channel', 'Flipkart': 'https://www.flipkart.com/search?q=I2C+Level+Shifter+4+Channel', 'Robu.in': 'https://robu.in/?s=I2C+Level+Shifter+4+Channel'},
    alternatives: ['COM-006'],
    tags: ['level-shifter', 'i2c', '3.3v', '5v', 'interface'],
    manufacturer: 'Generic',
    rating: 4.3,
    reviews: 5600,
  },
  {
    id: 'PWR-001',
    name: '18650 Li-Ion Battery 3.7V 3000mAh',
    part_number: '18650-3000',
    category: 'Electrical',
    subcategory: 'Power',
    description: 'Rechargeable 18650 lithium-ion cell, 3.7V nominal, 3000mAh. Standard cell for DIY power banks.',
    specifications: {'Voltage': '3.7V nominal (4.2V max)', 'Capacity': '3000 mAh', 'Chemistry': 'Li-Ion', 'Discharge': '10A max', 'Size': '18x65mm'},
    price_inr: 299,
    price_usd: 3.6,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 680,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=18650',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=18650+Li-Ion+Battery+3000mAh', 'Flipkart': 'https://www.flipkart.com/search?q=18650+Li-Ion+Battery+3000mAh', 'Robu.in': 'https://robu.in/?s=18650+Li-Ion+Battery+3000mAh'},
    alternatives: ['PWR-002'],
    tags: ['18650', 'battery', 'li-ion', 'rechargeable', 'power'],
    manufacturer: 'Generic',
    rating: 4.2,
    reviews: 9800,
  },
  {
    id: 'PWR-002',
    name: 'TP4056 Li-Ion Charger Module',
    part_number: 'TP4056',
    category: 'Electrical',
    subcategory: 'Power',
    description: 'USB Li-Ion/LiPo battery charger module with protection, 1A charge current, micro-USB input.',
    specifications: {'Charge Current': '1A', 'Input': 'Micro-USB 5V', 'Output': '4.2V', 'Protection': 'Overcharge/discharge/short', 'Indicator': 'LED'},
    price_inr: 79,
    price_usd: 1.0,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 720,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=TP4056',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=TP4056+Battery+Charger+Module', 'Flipkart': 'https://www.flipkart.com/search?q=TP4056+Battery+Charger+Module', 'Robu.in': 'https://robu.in/?s=TP4056+Battery+Charger+Module'},
    alternatives: ['PWR-001'],
    tags: ['tp4056', 'charger', 'li-ion', 'lipo', 'usb', 'protection'],
    manufacturer: 'Generic',
    rating: 4.4,
    reviews: 12400,
  },
  {
    id: 'PWR-003',
    name: 'LM7805 5V Voltage Regulator',
    part_number: 'LM7805',
    category: 'Electrical',
    subcategory: 'Power',
    description: 'Classic 5V linear voltage regulator, 1A output, TO-220 package. For regulated 5V power supply.',
    specifications: {'Output Voltage': '5V', 'Max Current': '1A', 'Input Voltage': '7-35V', 'Package': 'TO-220', 'Dropout': '2V'},
    price_inr: 29,
    price_usd: 0.3,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 1500,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=LM7805',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=LM7805+Voltage+Regulator', 'Flipkart': 'https://www.flipkart.com/search?q=LM7805+Voltage+Regulator', 'Robu.in': 'https://robu.in/?s=LM7805+Voltage+Regulator'},
    alternatives: ['PWR-004'],
    tags: ['lm7805', 'voltage-regulator', '5v', 'linear', 'to-220'],
    manufacturer: 'Texas Instruments',
    rating: 4.3,
    reviews: 15600,
  },
  {
    id: 'PWR-004',
    name: 'LM2596 Buck Converter Module',
    part_number: 'LM2596',
    category: 'Electrical',
    subcategory: 'Power',
    description: 'Adjustable step-down DC-DC converter, 4-40V input, 1.25-37V output, 3A. Efficient power supply.',
    specifications: {'Input': '4-40V', 'Output': '1.25-37V (adjustable)', 'Max Current': '3A', 'Efficiency': '92%', 'Frequency': '150 kHz'},
    price_inr: 149,
    price_usd: 1.8,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 480,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=LM2596',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=LM2596+Buck+Converter', 'Flipkart': 'https://www.flipkart.com/search?q=LM2596+Buck+Converter', 'Robu.in': 'https://robu.in/?s=LM2596+Buck+Converter'},
    alternatives: ['PWR-003'],
    tags: ['lm2596', 'buck-converter', 'dc-dc', 'adjustable', 'efficient'],
    manufacturer: 'Texas Instruments',
    rating: 4.4,
    reviews: 8900,
  },
  {
    id: 'PWR-005',
    name: 'MT3608 Boost Converter Module',
    part_number: 'MT3608',
    category: 'Electrical',
    subcategory: 'Power',
    description: 'Step-up DC-DC converter, 2-24V input, up to 28V output, 2A. For boosting battery voltage.',
    specifications: {'Input': '2-24V', 'Output': 'Up to 28V (adjustable)', 'Max Current': '2A', 'Efficiency': '93%'},
    price_inr: 99,
    price_usd: 1.2,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 340,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=MT3608',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=MT3608+Boost+Converter', 'Flipkart': 'https://www.flipkart.com/search?q=MT3608+Boost+Converter', 'Robu.in': 'https://robu.in/?s=MT3608+Boost+Converter'},
    alternatives: ['PWR-004'],
    tags: ['mt3608', 'boost-converter', 'step-up', 'dc-dc'],
    manufacturer: 'Generic',
    rating: 4.2,
    reviews: 5600,
  },
  {
    id: 'PWR-006',
    name: '9V Battery Clip Connector',
    part_number: '9V-CLIP',
    category: 'Electrical',
    subcategory: 'Power',
    description: 'Standard 9V battery snap connector with wire leads. For powering Arduino and small circuits.',
    specifications: {'Voltage': '9V', 'Wire Length': '15 cm', 'Connector': 'Snap-on', 'Wire Gauge': '26 AWG'},
    price_inr: 29,
    price_usd: 0.3,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 2000,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=9V+Clip',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=9V+Battery+Clip+Connector', 'Flipkart': 'https://www.flipkart.com/search?q=9V+Battery+Clip+Connector', 'Robu.in': 'https://robu.in/?s=9V+Battery+Clip+Connector'},
    alternatives: ['PWR-001'],
    tags: ['9v', 'battery', 'clip', 'connector', 'power'],
    manufacturer: 'Generic',
    rating: 4.1,
    reviews: 11200,
  },
  {
    id: 'TOL-001',
    name: '830-Point Solderless Breadboard',
    part_number: 'BB-830',
    category: 'Tools',
    subcategory: 'Prototyping',
    description: 'Full-size 830-point breadboard, 2 power rails, nickel-plated contacts. Essential for prototyping.',
    specifications: {'Points': '830', 'Tie Points': '630', 'Power Rails': '4x50', 'Material': 'ABS + Nickel-plated', 'Size': '165x55x9mm'},
    price_inr: 79,
    price_usd: 1.0,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 1200,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=Breadboard+830',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=830+Point+Breadboard', 'Flipkart': 'https://www.flipkart.com/search?q=830+Point+Breadboard', 'Robu.in': 'https://robu.in/?s=830+Point+Breadboard'},
    alternatives: ['TOL-002'],
    tags: ['breadboard', 'prototyping', 'solderless', '830-point'],
    manufacturer: 'Generic',
    rating: 4.4,
    reviews: 8900,
  },
  {
    id: 'TOL-002',
    name: '400-Point Mini Breadboard',
    part_number: 'BB-400',
    category: 'Tools',
    subcategory: 'Prototyping',
    description: 'Half-size 400-point breadboard. Compact for small projects and Arduino Nano builds.',
    specifications: {'Points': '400', 'Tie Points': '300', 'Power Rails': '2x25', 'Size': '83x55x9mm'},
    price_inr: 49,
    price_usd: 0.6,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 980,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=Breadboard+400',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=400+Point+Mini+Breadboard', 'Flipkart': 'https://www.flipkart.com/search?q=400+Point+Mini+Breadboard', 'Robu.in': 'https://robu.in/?s=400+Point+Mini+Breadboard'},
    alternatives: ['TOL-001'],
    tags: ['breadboard', 'mini', '400-point', 'compact', 'prototyping'],
    manufacturer: 'Generic',
    rating: 4.3,
    reviews: 7200,
  },
  {
    id: 'TOL-003',
    name: 'Jumper Wire Kit 120pcs',
    part_number: 'JW-120',
    category: 'Tools',
    subcategory: 'Wiring',
    description: '120-piece jumper wire kit: 40 M-M, 40 M-F, 40 F-F, 20cm, 10 colors. Essential for breadboard wiring.',
    specifications: {'Total': '120 pieces', 'Types': 'M-M, M-F, F-F', 'Length': '20 cm', 'Colors': '10', 'Gauge': '26 AWG'},
    price_inr: 99,
    price_usd: 1.2,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 950,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=Jumper+Wires',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=Jumper+Wire+Kit+120pcs', 'Flipkart': 'https://www.flipkart.com/search?q=Jumper+Wire+Kit+120pcs', 'Robu.in': 'https://robu.in/?s=Jumper+Wire+Kit+120pcs'},
    alternatives: ['TOL-004'],
    tags: ['jumper-wires', 'kit', 'm-m', 'm-f', 'f-f', 'prototyping'],
    manufacturer: 'Generic',
    rating: 4.3,
    reviews: 11200,
  },
  {
    id: 'TOL-004',
    name: 'Dupont Connector Kit 620pcs',
    part_number: 'DUPONT-KIT',
    category: 'Tools',
    subcategory: 'Wiring',
    description: '620-piece Dupont connector kit with crimping tool. For making custom cable lengths.',
    specifications: {'Total': '620 pieces', 'Includes': '2.54mm connectors + pins + housing', 'Tool': 'Crimping tool included'},
    price_inr: 299,
    price_usd: 3.6,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 280,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=Dupont+Kit',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=Dupont+Connector+Kit', 'Flipkart': 'https://www.flipkart.com/search?q=Dupont+Connector+Kit', 'Robu.in': 'https://robu.in/?s=Dupont+Connector+Kit'},
    alternatives: ['TOL-003'],
    tags: ['dupont', 'connector', 'crimping', 'custom-cables', '2.54mm'],
    manufacturer: 'Generic',
    rating: 4.2,
    reviews: 4800,
  },
  {
    id: 'TOL-005',
    name: 'Soldering Iron Kit 60W',
    part_number: 'SOLDER-60W',
    category: 'Tools',
    subcategory: 'Soldering',
    description: '60W adjustable temperature soldering iron with stand, solder wire, and tips. For permanent connections.',
    specifications: {'Power': '60W', 'Temperature': '200-450°C (adjustable)', 'Tip': '5 interchangeable tips', 'Includes': 'Stand + solder wire'},
    price_inr: 799,
    price_usd: 9.6,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 180,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=Soldering+Iron',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=Soldering+Iron+Kit+60W', 'Flipkart': 'https://www.flipkart.com/search?q=Soldering+Iron+Kit+60W', 'Robu.in': 'https://robu.in/?s=Soldering+Iron+Kit+60W'},
    alternatives: ['TOL-006'],
    tags: ['soldering', 'iron', '60w', 'adjustable', 'kit'],
    manufacturer: 'Generic',
    rating: 4.3,
    reviews: 6700,
  },
  {
    id: 'TOL-006',
    name: 'Solder Wire 60/40 0.8mm 100g',
    part_number: 'SOLDER-WIRE',
    category: 'Tools',
    subcategory: 'Soldering',
    description: '60/40 tin/lead solder wire, 0.8mm diameter, 100g reel with flux core. Standard electronics solder.',
    specifications: {'Composition': '60% Tin / 40% Lead', 'Diameter': '0.8 mm', 'Weight': '100g', 'Flux': 'Rosin core', 'Melting Point': '183°C'},
    price_inr: 199,
    price_usd: 2.4,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 420,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=Solder+Wire',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=Solder+Wire+60/40+0.8mm', 'Flipkart': 'https://www.flipkart.com/search?q=Solder+Wire+60/40+0.8mm', 'Robu.in': 'https://robu.in/?s=Solder+Wire+60/40+0.8mm'},
    alternatives: ['TOL-005'],
    tags: ['solder', 'wire', '60/40', 'flux', 'soldering'],
    manufacturer: 'Generic',
    rating: 4.4,
    reviews: 9800,
  },
  {
    id: 'TOL-007',
    name: 'Digital Multimeter',
    part_number: 'DMM-830',
    category: 'Tools',
    subcategory: 'Test Equipment',
    description: 'Auto-ranging digital multimeter, measures voltage/current/resistance/continuity/diode. Essential for debugging.',
    specifications: {'Measures': 'V, A, Ω, Continuity, Diode', 'Display': '3.5 digit LCD', 'DC Voltage': '200mV-600V', 'AC Voltage': '200V-600V', 'Current': '200µA-10A'},
    price_inr: 599,
    price_usd: 7.2,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 240,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=Multimeter',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=Digital+Multimeter', 'Flipkart': 'https://www.flipkart.com/search?q=Digital+Multimeter', 'Robu.in': 'https://robu.in/?s=Digital+Multimeter'},
    alternatives: ['TOL-008'],
    tags: ['multimeter', 'dmm', 'voltage', 'current', 'resistance', 'test'],
    manufacturer: 'Generic',
    rating: 4.4,
    reviews: 12400,
  },
  {
    id: 'TOL-008',
    name: 'Logic Analyzer 8-Channel USB',
    part_number: 'LA-8CH',
    category: 'Tools',
    subcategory: 'Test Equipment',
    description: '8-channel USB logic analyzer, 24MHz sample rate, compatible with Sigrok/PulseView. For debugging digital signals.',
    specifications: {'Channels': '8', 'Sample Rate': '24 MHz', 'Voltage': '0-5V', 'Interface': 'USB', 'Software': 'Sigrok / PulseView'},
    price_inr: 799,
    price_usd: 9.6,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 120,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=Logic+Analyzer',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=USB+Logic+Analyzer+8+Channel', 'Flipkart': 'https://www.flipkart.com/search?q=USB+Logic+Analyzer+8+Channel', 'Robu.in': 'https://robu.in/?s=USB+Logic+Analyzer+8+Channel'},
    alternatives: ['TOL-007'],
    tags: ['logic-analyzer', 'usb', '8-channel', 'debugging', 'digital', 'sigrok'],
    manufacturer: 'Generic',
    rating: 4.5,
    reviews: 5600,
  },
  {
    id: 'TOL-009',
    name: 'USB to TTL Serial Adapter (CP2102)',
    part_number: 'CP2102',
    category: 'Tools',
    subcategory: 'Interface',
    description: 'USB to UART serial adapter, CP2102 chip, 3.3V/5V selectable. For programming and debugging.',
    specifications: {'Chip': 'CP2102', 'Interface': 'USB ↔ UART', 'Voltage': '3.3V / 5V selectable', 'Baud Rate': 'Up to 921600', 'OS': 'Windows/Mac/Linux'},
    price_inr: 149,
    price_usd: 1.8,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 560,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=CP2102',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=CP2102+USB+to+TTL+Serial', 'Flipkart': 'https://www.flipkart.com/search?q=CP2102+USB+to+TTL+Serial', 'Robu.in': 'https://robu.in/?s=CP2102+USB+to+TTL+Serial'},
    alternatives: ['TOL-010'],
    tags: ['cp2102', 'usb-ttl', 'uart', 'serial', 'programmer'],
    manufacturer: 'Silicon Labs',
    rating: 4.4,
    reviews: 8900,
  },
  {
    id: 'TOL-010',
    name: 'USB to TTL Serial Adapter (CH340)',
    part_number: 'CH340G',
    category: 'Tools',
    subcategory: 'Interface',
    description: 'USB to UART adapter with CH340G chip. Budget alternative to CP2102 for Arduino programming.',
    specifications: {'Chip': 'CH340G', 'Interface': 'USB ↔ UART', 'Voltage': '3.3V / 5V', 'Baud Rate': 'Up to 2Mbps'},
    price_inr: 99,
    price_usd: 1.2,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 780,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=CH340',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=CH340+USB+to+TTL+Serial', 'Flipkart': 'https://www.flipkart.com/search?q=CH340+USB+to+TTL+Serial', 'Robu.in': 'https://robu.in/?s=CH340+USB+to+TTL+Serial'},
    alternatives: ['TOL-009'],
    tags: ['ch340', 'usb-ttl', 'uart', 'serial', 'programmer', 'budget'],
    manufacturer: 'WCH',
    rating: 4.2,
    reviews: 12400,
  },
  {
    id: 'MEC-001',
    name: '2WD Robot Car Chassis Kit',
    part_number: 'CHASSIS-2WD',
    category: 'Mechanical',
    subcategory: 'Chassis',
    description: 'Complete 2WD robot chassis with 2 DC motors, 2 wheels, caster, battery holder, and acrylic base.',
    specifications: {'Wheels': '2 + 1 caster', 'Motors': '2x DC gear motors', 'Material': 'Acrylic', 'Battery': '4x AA holder', 'Speed': 'Variable'},
    price_inr: 499,
    price_usd: 6.0,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 280,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=2WD+Chassis',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=2WD+Robot+Car+Chassis+Kit', 'Flipkart': 'https://www.flipkart.com/search?q=2WD+Robot+Car+Chassis+Kit', 'Robu.in': 'https://robu.in/?s=2WD+Robot+Car+Chassis+Kit'},
    alternatives: ['MEC-002'],
    tags: ['chassis', '2wd', 'robot', 'car', 'kit', 'acrylic'],
    manufacturer: 'Generic',
    rating: 4.2,
    reviews: 6800,
  },
  {
    id: 'MEC-002',
    name: '4WD Robot Car Chassis Kit',
    part_number: 'CHASSIS-4WD',
    category: 'Mechanical',
    subcategory: 'Chassis',
    description: '4WD robot chassis with 4 DC motors, 4 wheels, aluminum base. More stable than 2WD.',
    specifications: {'Wheels': '4', 'Motors': '4x DC gear motors', 'Material': 'Aluminum', 'Battery': 'Holder included', 'Speed': 'Variable'},
    price_inr: 799,
    price_usd: 9.6,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 180,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=4WD+Chassis',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=4WD+Robot+Car+Chassis+Kit', 'Flipkart': 'https://www.flipkart.com/search?q=4WD+Robot+Car+Chassis+Kit', 'Robu.in': 'https://robu.in/?s=4WD+Robot+Car+Chassis+Kit'},
    alternatives: ['MEC-001'],
    tags: ['chassis', '4wd', 'robot', 'car', 'aluminum', 'kit'],
    manufacturer: 'Generic',
    rating: 4.3,
    reviews: 4900,
  },
  {
    id: 'MEC-003',
    name: 'Robotic Arm Kit (4-DOF)',
    part_number: 'ARM-4DOF',
    category: 'Mechanical',
    subcategory: 'Robotic Arms',
    description: '4-degree-of-freedom robotic arm kit with 4 servo motors, acrylic frame, and assembly hardware.',
    specifications: {'DOF': '4', 'Servos': '4x SG90', 'Material': 'Acrylic', 'Payload': 'Up to 100g', 'Assembly': 'Required'},
    price_inr: 1299,
    price_usd: 15.7,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 85,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=Robotic+Arm',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=4DOF+Robotic+Arm+Kit', 'Flipkart': 'https://www.flipkart.com/search?q=4DOF+Robotic+Arm+Kit', 'Robu.in': 'https://robu.in/?s=4DOF+Robotic+Arm+Kit'},
    alternatives: ['ACT-006'],
    tags: ['robotic-arm', '4dof', 'servo', 'acrylic', 'kit'],
    manufacturer: 'Generic',
    rating: 4.1,
    reviews: 3200,
  },
  {
    id: 'MEC-004',
    name: 'Aluminum Standoff Kit M3 (120pcs)',
    part_number: 'STANDOFF-M3',
    category: 'Mechanical',
    subcategory: 'Hardware',
    description: '120-piece M3 aluminum standoff kit: 6mm, 10mm, 15mm, 20mm lengths with screws and nuts.',
    specifications: {'Material': 'Aluminum', 'Thread': 'M3', 'Lengths': '6/10/15/20mm', 'Total': '120 pieces', 'Includes': 'Screws + nuts'},
    price_inr: 199,
    price_usd: 2.4,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 420,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=Standoffs',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=M3+Aluminum+Standoff+Kit', 'Flipkart': 'https://www.flipkart.com/search?q=M3+Aluminum+Standoff+Kit', 'Robu.in': 'https://robu.in/?s=M3+Aluminum+Standoff+Kit'},
    alternatives: ['MEC-004'],
    tags: ['standoff', 'm3', 'aluminum', 'hardware', 'pcb', 'mounting'],
    manufacturer: 'Generic',
    rating: 4.4,
    reviews: 5600,
  },
  {
    id: 'MEC-005',
    name: 'Rubber Wheel 65mm (pair)',
    part_number: 'WHEEL-65',
    category: 'Mechanical',
    subcategory: 'Wheels',
    description: '65mm diameter rubber wheels with D-shaft hub. Compatible with most DC gear motors.',
    specifications: {'Diameter': '65 mm', 'Width': '27 mm', 'Hub': 'D-shaft 3mm', 'Material': 'Rubber + ABS', 'Pair': '2 wheels'},
    price_inr: 149,
    price_usd: 1.8,
    currency: 'INR',
    availability: 'in_stock',
    stock_qty: 340,
    image_url: 'https://placehold.co/300x300/1f2937/06b6d4?text=Wheels',
    datasheet_url: undefined,
    buy_urls: {'Amazon': 'https://www.amazon.in/s?k=65mm+Robot+Wheels+Pair', 'Flipkart': 'https://www.flipkart.com/search?q=65mm+Robot+Wheels+Pair', 'Robu.in': 'https://robu.in/?s=65mm+Robot+Wheels+Pair'},
    alternatives: ['MEC-001'],
    tags: ['wheels', '65mm', 'rubber', 'robot', 'd-shaft'],
    manufacturer: 'Generic',
    rating: 4.2,
    reviews: 4100,
  },
];

export function searchCatalog(query: string): CatalogProduct[] {
  if (!query.trim()) return CATALOG_DATA;
  const q = query.toLowerCase();
  return CATALOG_DATA.filter(p =>
    p.name.toLowerCase().includes(q) ||
    p.subcategory.toLowerCase().includes(q) ||
    p.description.toLowerCase().includes(q) ||
    p.tags.some(t => t.includes(q)) ||
    p.manufacturer.toLowerCase().includes(q) ||
    p.part_number.toLowerCase().includes(q)
  );
}

export function getCatalogByCategory(cat: string): CatalogProduct[] {
  if (cat === 'All') return CATALOG_DATA;
  return CATALOG_DATA.filter(p => p.category === cat);
}

export function getCatalogForProject(names: string[]): CatalogProduct[] {
  const results: CatalogProduct[] = [];
  const seen = new Set<string>();
  for (const name of names) {
    const q = name.toLowerCase();
    const match = CATALOG_DATA.find(p =>
      !seen.has(p.id) && (
        p.name.toLowerCase().includes(q) ||
        q.includes(p.name.toLowerCase().split(' ')[0].toLowerCase()) ||
        p.tags.some(t => q.includes(t) || t.includes(q.split(' ')[0]))
      )
    );
    if (match) { seen.add(match.id); results.push(match); }
  }
  return results;
}